### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by KiaraGrouwstra** [tycho01/synthesis#19]
I want green checkmarks on my commits. I've had good experience with [Travis + Docker](https://github.com/tycho01/sat-sudoku/blob/master/.travis.yml).
edit: Docker seemed less good for generating docs (#20), so I just went for a Haskell Travis, but build is [green](https://travis-ci.com/tycho01/synthesis/builds/146519703)!
edit 2: since the switch to Nix for HaskTorch CI is back [in progress](https://github.com/tycho01/synthesis/commits/travis-nix) again...

**Comment by tycho01** [comment]
Docker seemed less good for generating docs (#20), so I just went for a Haskell Travis, but build is [green](https://travis-ci.com/tycho01/synthesis/builds/146519703)!

**Comment by KiaraGrouwstra** [comment]
merged, now using the Cachix Github action as per HaskTorch's [`nix-linux` workflow](https://github.com/hasktorch/hasktorch/blob/42ec1031661f752c45048902bcff447608f07bbc/.github/workflows/nix-linux.yml).
restoring documentation (#20) remains todo.
