### ISSUE TITLE
Hint concurrent instances

### ISSUE THREAD

**Issue by KiaraGrouwstra** [tycho01/synthesis#34]
Currently my synthesizer runs into [synthesizer: This version of GHC is not thread-safe,can't safely run two instances of the interpreter simultaneously](https://github.com/haskell-hint/hint/issues/68).
running with `--bestOf=1` seemed a temp workaround yet still fails.
Unfortunately `cabal` won't let me use their [good branch](https://github.com/haskell-hint/hint/tree/ghc-8.10) off Github either...

ideas:
- ditch Cabal in favor of Stack/Nix for better dep management + Github branches?
  - ~this also needs GHC 8.10 for Hint's Github branch, which [also isn't available yet](https://github.com/hasktorch/hasktorch/pull/282) with HaskTorch~ [fixed](https://github.com/hasktorch/hasktorch/pull/353)
- include deps in nix, see [this branch](https://github.com/tycho01/synthesis/compare/hint-nix?expand=1); I haven't quite figured this out yet.

edit: `hint-0.9.0.3` fixes this, and should allow me to fully switch to Tasty, once Nix supports GHC 8.10 (#35).

**Comment by KiaraGrouwstra** [comment]
putting the whole thing in one Hint `Interpreter` monad seems to have fixed this.

**Comment by KiaraGrouwstra** [comment]
solving this comes at the expense of using `timeout` to solve infinite types... ugh.

**Comment by KiaraGrouwstra** [comment]
some discussion on `hint` + `timeout` [here](https://github.com/haskell-hint/hint/issues/94).

**Comment by gelisam** [comment]
> cabal won't let me use their good branch off Github 

I was able to configure a cabal project to use that branch by following [these instructions](https://dev.to/piq9117/using-github-repos-as-haskell-dependency-m2o), plus a `branch: dbb878955528d9125a601773b25a3c45b9fcef06`. `branch: ghc-8.10` didn't work, I had to use the commit hash.

**Comment by KiaraGrouwstra** [comment]
that's awesome, I'll try that -- thanks! :smile:
